name: Homebrew
on: [pull_request]
jobs:
  install:
    runs-on: macos-11.0
    strategy:
      matrix:
        formula:
          - python@2.7
          - python@3.5
          - python@3.6
          - python@3.10
    steps:
      - uses: actions/checkout@v2

      - name: Use Xcode 12.2
        run: sudo xcode-select -s /Applications/Xcode_12.2.app

      - name: Update Homebrew
        run: brew update

      - name: Install ${{ matrix.formula }}
        run: brew install -s -v ./Formula/${{ matrix.formula }}.rb

      - name: Test ${{ matrix.formula }}
        run: brew test ${{ matrix.formula }}

      - name: Audit ${{ matrix.formula }}
        run: brew audit --strict --online ${{ matrix.formula }}
